### ISSUE TITLE
Merge in latest SlickGrid features

### ISSUE THREAD

**Issue by philippjfr** [bokeh/SlickGrid#3]
I've tried looking around for the historical reasoning behind forking SlickGrid since I've completely forgotten the discussion here. The 6pac fork of SlickGrid that this fork is based on is still actively maintained and has introduced a range of new features and bug fixes. More specifically this was forked at 2.3.7 but there have now been 2.3.7-2.3.23 and 2.4.0-2.4.27 releases on the original fork, i.e. this fork is 53 releases behind.

Since I'm missing context I have a few questions:

1) Why did we have to fork it in the first place?
2) Are there major obstacles to merging in all the changes from the original fork?
3) Are there any obstacles to switching back to the evidently quite well maintained original fork?

The main feature out of the original fork I'd like to see here are frozen rows/columns.

Cc: @mattpap @bryevdv

**Comment by mattpap** [comment]
The main reasons for having a fork is lack of modularization and handling of dependencies (jquery, etc.), e.g. code like this:
```js
$.extend(true, window, {
    "Slick": {
    "Event": Event,
    "EventData": EventData,
    "EventHandler": EventHandler,
    "Range": Range,
    "NonDataRow": NonDataItem,
    "Group": Group,
    "GroupTotals": GroupTotals,
    "EditorLock": EditorLock,
    (...)
})
```
It seems that they didn't make any progress in those areas in the meantime. I would be happy to drop this fork and just depend on npm package of slickgrid, but for that I need proper ESM (or at least commonjs) modules to depend on. At the time, it wasn't a viable option to contribute to slickgrid, but I think it would be the best option now, assuming the current maintainer would consider modularization.

**Comment by philippjfr** [comment]
Thanks, that makes sense, I did suspect it was some important technical reason. Would be good to file an issue with the original fork to get that discussion going. I'd do it but suspect I'd leave out important technical discussion so maybe it's best if you did it? In the meantime how hard do you think it would be for me to port some of the latest changes here?

**Comment by mattpap** [comment]
>  In the meantime how hard do you think it would be for me to port some of the latest changes here?

I will do a quick merge and it will reveal the amount of work needed (ranging from no work to starting from scratch). On top of that there may be changes needed to bokehjs' code as well.

**Comment by philippjfr** [comment]
I tried just switching bokeh over to `slickgrid` instead of `@bokeh/slickgrid` and got some less errors:

```
    RuntimeError: error evaluating function `alpha`: Argument cannot be evaluated to a color in /Users/philippjfr/development/bokeh/bokehjs/node_modules/slickgrid/slick.grid.css on line 186, column 11:
    185   opacity: 0.15;
    186   filter: alpha(opacity = 15);
    187   cursor: move;

    [14:06:15] failed: There were 1 Less errors:
    RuntimeError: error evaluating function `alpha`: Argument cannot be evaluated to a color in /Users/philippjfr/development/bokeh/bokehjs/node_modules/slickgrid/slick.grid.css on line 186, column 11:
    185   opacity: 0.15;
    186   filter: alpha(opacity = 15);
    187   cursor: move
```

Everything else seemed okay but I guess I don't know if it tries to compile the CSS first and then aborts.

**Comment by philippjfr** [comment]
Also I'll have to make changes to Bokeh anyway to expose some of the new features.

**Comment by mattpap** [comment]
> filter: alpha(opacity = 15);

This is IE/MS proprietary syntax, so I just removed this in the fork.

**Comment by mattpap** [comment]
I did the merge and it wasn't too bad, though I had to reapply my changes on top of the fresh `master` for simplicity, which will inevitable result in a force push to the default branch (`bokeh`), but that shouldn't matter in such a obscure repository. I should be able to finish this later today or tomorrow.

**Comment by philippjfr** [comment]
Awesome, really appreciate it! I'll work on exposing some of the new features in Bokeh as soon as that's done.
